#!/bin/bash

# coinmarketcap_crypto_price_parser

COINS_FILE=/tmp/coinmarketcap_coins

# return list of supported coins
curl -s "https://coinmarketcap.com/" -H "Accept-Encoding: gzip,deflate,sdch" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cookie: <>" -H "Connection: keep-alive" -H "Cache-Control: max-age=0" --compressed | tr '/ ' '_' | tr '<' '\n' | grep "cmc-link" | grep "currencies" | grep "class" | grep -v "markets" | grep -v "period" | grep -v "fiat" | tr '"' '\n' | grep "currencies" | tr '_' '\n' | grep -v "currencies" | grep -v "sitemap" > /tmp/coinmarketcap

# remove empty lines
awk 'NF > 0' /tmp/coinmarketcap > ${COINS_FILE}

RESULTS_JSON=results_json
echo "{" > ${RESULTS_JSON}

LAST_ITEM=1
for ITEM in `cat ${COINS_FILE}`
do
# get coin data
RESULT=`curl -s "https://coinmarketcap.com/currencies/${ITEM}/markets/" -H "Accept-Encoding: gzip,deflate,sdch" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cookie: <>" -H "Connection: keep-alive" -H "Cache-Control: max-age=0" --compressed | tr '<' '\n' | grep "priceValue" | tr '>' '\n' | grep -v " "`
[[ $LAST_ITEM -eq 100 ]] && echo "\"${ITEM}\":\"${RESULT}\"" >> ${RESULTS_JSON}
[[ $LAST_ITEM -ne 100 ]] && [[ ${RESULT} != "" ]] && echo "\"${ITEM}\":\"${RESULT}\"," >> ${RESULTS_JSON}
#echo "\"${ITEM}\":\"${RESULT}\""
LAST_ITEM=$(($LAST_ITEM+1))
done
echo "}" >> ${RESULTS_JSON}

cat ${RESULTS_JSON}

# bash coinmarketcap_crypto_price_parser
