#!/bin/bash

# images_query

TARGET_URL=${1}

curl -s "${TARGET_URL}" -H "Accept-Encoding: gzip,deflate,sdch" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cookie: <>" -H "Connection: keep-alive" -H "Cache-Control: max-age=0" --compressed | grep "<img"| tr "'" '\n' | tr ',=";&(? ' '\n' | grep "https" > /tmp/image_list

#cat /tmp/image_list


curl -s "${TARGET_URL}" -H "Accept-Encoding: gzip,deflate,sdch" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cookie: <>" -H "Connection: keep-alive" -H "Cache-Control: max-age=0" --compressed | grep "<img" | tr ',="' '\n' | grep -v "alt" > /tmp/image_list_partial #| tr "'" '\n' | tr ',=";&(? ' '\n' > /tmp/image_list
# curl -s "https://www.bitcoinblockhalf.com" -H "Accept-Encoding: gzip,deflate,sdch" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cookie: <>" -H "Connection: keep-alive" -H "Cache-Control: max-age=0" --compressed | grep "<img" | tr ',="' '\n' | grep -v "alt" > /tmp/headline_images; cat /tmp/headline_images


# TODO need to append TARGET URL to get full path images for image_list_partial
#for ITEM in `grep -E ".jpg" /tmp/image_list`
#do
#[[ `echo ${ITEM} | tr '.' ' ' | awk '{print $NF}'` == "jpg" ]] && echo ${ITEM}
#done
> /tmp/resulting_images
grep -E ".png" /tmp/image_list_partial >> /tmp/resulting_images
grep -E ".jpeg" /tmp/image_list_partial >> /tmp/resulting_images
grep -E ".jp2" /tmp/image_list_partial >> /tmp/resulting_images
grep -E ".svg" /tmp/image_list_partial >> /tmp/resulting_images
grep -E ".gif" /tmp/image_list_partial >> /tmp/resulting_images



# .svg .png .jp2 .jpeg .gif .jpg
grep -E ".png" /tmp/image_list >> /tmp/resulting_images
grep -E ".jpeg" /tmp/image_list >> /tmp/resulting_images
grep -E ".jp2" /tmp/image_list >> /tmp/resulting_images
grep -E ".svg" /tmp/image_list >> /tmp/resulting_images
grep -E ".gif" /tmp/image_list >> /tmp/resulting_images
# exclude amazon incorrect file extension images
for ITEM in `grep -E ".jpg" /tmp/image_list`
do
[[ `echo ${ITEM} | tr '.' ' ' | awk '{print $NF}'` == "jpg" ]] && echo ${ITEM} >> /tmp/resulting_images
done

> /tmp/final_images
for ITEM in `cat /tmp/resulting_images`
do
[[ `echo ${ITEM} | tr ':' ' ' | awk '{print $1}' | grep http` == "" ]] && {
[[ `echo ${ITEM:0:2}` != ".." ]] && echo ${1}${ITEM} >> /tmp/final_images
[[ `echo ${ITEM:0:2}` == ".." ]] && echo ${1}${ITEM:2:${#ITEM}} >> /tmp/final_images
}
[[ `echo ${ITEM} | tr ':' ' ' | awk '{print $1}' | grep http` != "" ]] && echo ${ITEM} >> /tmp/final_images
done


uniq /tmp/final_images /tmp/final_images_uniq

#[[ ${} ]]

IMAGES_FILE=/tmp/final_images_uniq
RESULTS_JSON=results_images_json

echo "{" > ${RESULTS_JSON}

NUMBER_OF_ITEMS=$((`wc -l ${IMAGES_FILE} | awk '{print $1}'`+1))

LAST_ITEM=2
for ITEM in `cat ${IMAGES_FILE}`
do
echo "$LAST_ITEM  $NUMBER_OF_ITEMS"
[[ $LAST_ITEM -eq $NUMBER_OF_ITEMS ]] && echo "\"${ITEM}\":\"\"" >> ${RESULTS_JSON}
[[ $LAST_ITEM -ne $NUMBER_OF_ITEMS ]] && echo "\"${ITEM}\":\"\"," >> ${RESULTS_JSON}
LAST_ITEM=$(($LAST_ITEM+1))
done
echo "}" >> ${RESULTS_JSON}

cat ${RESULTS_JSON}



# bash images_query https://www.bitcoinblockhalf.com

# bash images_query https://www.amazon.com/XFX-Speedster-SWFT210-Graphics-RX-66XT8DFDQ/dp/B09B17SQBS

# bash images_query https://www.coursera.org

# bash images_query https://www.elastic.co/

# bash images_query https://www.coinglass.com
