#!/bin/bash

# Copyright (c) 2021 Michael Neill Hartman. All rights reserved.
# mnh_license@proton.me
# https://github.com/hartmanm

# launch_da

# configure amazon_items and newegg_items files to have one item url per line

# to run, 
# cd <to cloned repo directory>
# bash launch_da

initial_update(){
bash images_query https://www.bitcoinblockhalf.com 
bash amazon_item_query_wrapper amazon_items 
bash newegg_item_query_wrapper newegg_items 
#bash coinmarketcap_crypto_price_parser 
#bash images_query https://news.google.com/topstories?hl=en-US&gl=US&ceid=US:en 
#bash google_news_headlines 
bash join_results 
}

initial_update
